# Generated by Django 3.2.4 on 2021-06-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('source', models.CharField(max_length=500)),
                ('url', models.URLField()),
                ('added_on', models.DateTimeField()),
                ('source_type', models.CharField(choices=[('book', 'Book'), ('website', 'Website'), ('research_paper', 'Research Paper'), ('pdf', 'PDF')], max_length=25)),
            ],
        ),
    ]
